name: "Deploy-docker"

on:
  workflow_dispatch:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: onfinality
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get updated network-indexer-metrics version
        id: fetch-version
        run: |
          sh .github/scripts/fetchVersion.sh

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: amd64
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: onfinality/networkd_bootstrap:v${{ steps.fetch-version.outputs.VERSION }}
          build-args: RELEASE_VERSION=${{ steps.fetch-version.outputs.VERSION }}
          ssh: default

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
